// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_MgiOWuVpU9c66fxcHppCRmOH3eR2gSw',
    appId: '1:8875696772:web:f3f006a07477719639d8d1',
    messagingSenderId: '8875696772',
    projectId: 'es-app-d6cd7',
    authDomain: 'es-app-d6cd7.firebaseapp.com',
    storageBucket: 'es-app-d6cd7.firebasestorage.app',
    measurementId: 'G-J779EBWV8R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCm_Ybcjn1AjHVsVcbN0zkgmcBVOaspSLM',
    appId: '1:8875696772:android:10cb77abf376f2b239d8d1',
    messagingSenderId: '8875696772',
    projectId: 'es-app-d6cd7',
    storageBucket: 'es-app-d6cd7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC58BliEQWV2ypEAyL0j4WWzP-IYfBvP9w',
    appId: '1:8875696772:ios:28dbd99cea62e3b139d8d1',
    messagingSenderId: '8875696772',
    projectId: 'es-app-d6cd7',
    storageBucket: 'es-app-d6cd7.firebasestorage.app',
    iosBundleId: 'com.example.esApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC58BliEQWV2ypEAyL0j4WWzP-IYfBvP9w',
    appId: '1:8875696772:ios:28dbd99cea62e3b139d8d1',
    messagingSenderId: '8875696772',
    projectId: 'es-app-d6cd7',
    storageBucket: 'es-app-d6cd7.firebasestorage.app',
    iosBundleId: 'com.example.esApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_MgiOWuVpU9c66fxcHppCRmOH3eR2gSw',
    appId: '1:8875696772:web:26bca65c3ccd0d4639d8d1',
    messagingSenderId: '8875696772',
    projectId: 'es-app-d6cd7',
    authDomain: 'es-app-d6cd7.firebaseapp.com',
    storageBucket: 'es-app-d6cd7.firebasestorage.app',
    measurementId: 'G-Y825E10M5B',
  );

}